name: cv-demo
namespace: ${infra.kubernetes.namespace}

image: ${artifact.metadata.image}

env:
  config:
    # Override in environment with ingress controller load balancer IP or host
    # E.g http://a8241cbf8317f4c1ab5507fbce9d576c-671821569.us-east-2.elb.amazonaws.com:8080/
    ALLOWED_ORIGINS: http://ac476ec2e5ac44df0aa536189f9e9308-197376168.us-east-1.elb.amazonaws.com:8080/
    
